name: Label new incidents as intake
on:
  issues:
    types: [opened]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add intake label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: intake
